Resources:

  User:
    Type: AWS::IAM::User
    Properties:
      UserName: example-user
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess

      Policies:
        - PolicyName: example-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: IamListAccess
                Effect: Allow
                Action:
                  - iam:ListRoles
                  - iam:ListUsers
                Resource: "*"

  MyInlinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: example-inline-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:*
            Resource: "*"
      Users:
        - !Ref User

  MySecondInlinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: example-second-inline-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource: "*"
      Users:
        - !Ref User