AWSTemplateFormatVersion: 2010-09-09
Description: Create A Role For US to assume and create resource we 'll have access to
parameters:
  BucketName:
    Type: string
    Default: "sts-fun-example-456"
Resources:
  StsRole:
    Type: " arn:aws:iam::283277657906:user/STS-example"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: s3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource:
                  [
                    !Sub "arn:aws:s3:::${BucketName}",
                    !Sub "arn:aws:s3:::${BucketName/*}",
                  ]
