AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ContainerLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: ./
      Dockerfile: Dockerfile
      SamResourceId: Inlinelamda
    Properties:
      PackageType: Image
      ImageUri: 283277657906.dkr.ecr.eu-north-1.amazonaws.com/python-container-example:latest