#!/usr/bin/env bash

# create our vpc 

$VPC_ID=(aws ec2 create-vpc --cidr-block "172.1.0.0/16" --region eu-north-1 --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-0}]' --query Vpc.VpcId --output text)

echo $VPC_ID
# enables the DNS Hostname for VPC 

aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames Value=true
# create an IGW 

$IGW_ID=(aws ec2 create-internet-gateway  --query InternetGateway.InternetGatewayId --output text) 
echo $IGW_ID
# attach our IGW 

aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID
# create a new subnet 

$SUB_ID=(aws ec2 create-subnet --vpc-id $VPC_ID --cidr-block "172.1.0.0/16" --query "Subnet.SubnetId" --output text)
echo $SUB_ID
# auto-assign IPV4 

aws ec2 modify-subnet-attribute --subnet-id $SUB_ID --map-public-ip-on-launch
# get the route table ID

$RT_ID=(aws ec2 describe-route-tables --filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" --query "RouteTables[0].RouteTableId" --output text)
echo $RT_ID
# explicty associate subnet 

aws ec2 associate-route-table --route-table-id $RT_ID --subnet-id $SUB_ID
# add a route for our RT to our IGW 

aws ec2 create-route --route-table-id $RT_ID --destination-cidr-block "0.0.0.0/0" --gateway-id $IGW_ID
