#!/usr/bin/env bash 

echo "=== Clearing Bucket ===" 

BUCKET_NAME=$1

# check for the bucket name is provided or not  
if [ -z "$BUCKET_NAME" ]; then
    echo "U need to spcify the bucket name" 
    exit 2
fi 

aws s3 rm s3://$BUCKET_NAME --recursiv