#!/usr/bin/env bash 

echo " === Create A Bucket ===" 

BUCKET_NAME=$1
BUCKET_REGION=$2


# check for the bucket name is provided or not  
if [ -z "$BUCKET_NAME" ]; then
    echo "U need to spcify the bucket name" 
    exit 2
fi 

# check for the region argument is provided or not 
if [ -z "$BUCKET_REGION" ]; then
    echo "U need to spcify the region" 
    exit 2 
fi

aws s3api create-bucket --bucket $BUCKET_NAME --region $BUCKET_REGION --create-bucket-configuration LocationConstraint=$BUCKET_REGION

