#!/usr/bin/env bash 


BUCKET_NAME=$1
FILE_NAME=$2
FILE_PATH=$3

# check for the bucket name is provided or not  
if [ -z "$BUCKET_NAME" ]; then
    echo "U need to spcify the bucket name" 
    exit 2
fi 

# check for the file name is provided or not  
if [ -z "$FILE_PATH" ]; then
    echo "U need to spcify the file path" 
    exit 2
fi 

# the command 
aws s3api put-object --bucket $BUCKET_NAME --key $FILE_NAME --body $FILE_PATH

echo "File '$FILE_NAME' uploaded successfully to '$BUCKET_NAME'"