#!/usr/bin/env bash 


BUCKET_NAME=$1
FILE_NAME=$2

# check for the bucket name is provided or not  
if [ -z "$BUCKET_NAME" ]; then
    echo "U need to spcify the bucket name" 
    exit 2
fi 

# check for the file name is provided or not  
if [ -z "$FILE_NAME" ]; then
    echo "U need to spcify the file name" 
    exit 2
fi 

# the command 
aws s3api put-object --bucket $BUCKET_NAME --body $FILE_NAME