#!/usr/bin/env bash 


echo "==== deploy RDS Basic ===="


STACK_NAME="RDS-Basic"

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region eu-north-1 \
--stack-name $STACK_NAME