AWSTemplateFormatVersion: "2010-09-09"

Description: EC2 with Redis and SSM

Parameters:

  InstanceType:
    Type: String
    Default: t3.micro

  VpcId:
    Type: String
    Default: vpc-0ca79c10ec4123590

  SubnetId:
    Type: String
    Default: subnet-0741dac532f7c1446

  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0a905b99668efea4b

  SecurityGroupId:
    Type: String
    Default: sg-0098231e1c473e71e

Resources:

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId

      SecurityGroupIds:
        - !Ref SecurityGroupId

      IamInstanceProfile: !Ref InstanceProfile

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          dnf update -y

          dnf install -y redis6

          systemctl enable redis6
          systemctl start redis6

      Tags:
        - Key: Name
          Value: Redis-WebServer

Outputs:

  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref WebServer

  PrivateIP:
    Description: EC2 Private IP
    Value: !GetAtt WebServer.PrivateIp

  PublicIP:
    Description: EC2 Public IP
    Value: !GetAtt WebServer.PublicIp