AWSTemplateFormatVersion: 2010-09-09
Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html
  S3Bucket:
    Type: "AWS::S3::Bucket"
    # aws generate a random bucket name for us ==> so we do not need to spacify one for it
